### Override local settings in `.mise.local.toml` which is untracked by git

[tools]
bun = '1'

[settings]
status.show_env = true
status.show_tools = true
legacy_version_file = true

[[env]]
_.file = '.env'
DEBUG = 'eslint:eslint'
[[env]]
_.file = '.env.development'
